### ISSUE TITLE
 Could not execute GraphicsMagick/ImageMagick

### ISSUE THREAD

**Issue by taileshrbamankar** [flovilmart/parse-image#16]
I getting this error :

Error generating response. ParseError {
  code: 141,
  message: [Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found] }

I deployed my application of aws elasticbeanstalk.

Below are cloud code to Generate thumbnail using aws photo url and save thumbnail to parse file

var Image = require("parse-image");
var request = require('request');

Parse.Cloud.define("TestImageCropFuntion", function(request, response) {
    var fs = require('fs'),
    im = require('imagemagick');
    var albumobjct = request.params.imageurl;
    // response.success(albumobjct);
    var image_url = albumobjct._url;
    var image_name = albumobjct._name;
    Parse.Cloud.httpRequest({
      url: image_url
    }).then(function(response) {
        var image = new Image();
        return image.setData(response.buffer);
    }).then(function(image) {
        /_Crop the image to the smaller of width or height._/
        var size = Math.min(image.width(), image.height());
        return image.crop({
            left: (image.width() - size) / 2,
            top: (image.height() - size) / 2,
            width: size,
            height: size
        });
    }).then(function(image) {
        /_Resize the image to 64x64._/
        return image.scale({
            width: 500, //250
            height: 500 //250
        });
    }).then(function(image) {
        /_Make sure it's a JPEG to save disk space and bandwidth._/
        return image.setFormat("JPEG");
    }).then(function(image) {
        /\* Get the image data in a Buffer._/
        return image.data();
    }).then(function(buffer) {
        /_Save the image into a new file.*/
        var base64 = buffer.toString("base64");
        var cropped = new Parse.File(image_name, {
            base64: base64
        });
        return cropped.save({useMasterKey: true});
    }).then(function(cropped) {
        response.success(cropped._url);
    }).then(function(result) {
        console.log("result final then" + result);
    }, function(error) {
        response.error(error);
    });
});

**Comment by junal** [comment]
I'm having exact same issue. @flovilmart Any idea?

**Comment by flovilmart** [comment]
I'm not sure as it's on elastic beanstalk. you should probably look at the error and see what's the issue there.

**Comment by junal** [comment]
@flovilmart Error is same as above. Here's my full error.

> 2016-11-25T16:20:35.661Z - Error generating response. ParseError {
  code: 141,
  message: 
   Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
       at ChildProcess.<anonymous> (/root/pgx/node_modules/gm/lib/command.js:299:14)
       at emitOne (events.js:96:13)
       at ChildProcess.emit (events.js:188:7)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
       at onErrorNT (internal/child_process.js:359:16)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickDomainCallback (internal/process/next_tick.js:122:9) }

>

**Comment by flovilmart** [comment]
And as you can see it's generated by the gm module, not parse-image.

**Comment by junal** [comment]
I have no clue about GM. Tried uninstalling and re-installing. Same result.

**Comment by flovilmart** [comment]
What I'm trying to say is that the problem lies into the gm module, not this module. I'm not sure how this is different on elastic beanstalk, or if this package can be deployed there.

**Comment by junal** [comment]
@taileshrbamankar did you find any solution?

**Comment by JongSeok-Kim** [comment]
I'm having exact same issue.

**Comment by anoopmundathan** [comment]
Same issue for me as well
