### ISSUE TITLE
error when using amazon s3 adapter

### ISSUE THREAD

**Issue by funkenstrahlen** [flovilmart/parse-image#19]
I use the following code to generate thumbnails of my coverarts:

```js
function generateThumbnail(channel, size, coverartAttribute){
	if (!channel.has(coverartAttribute)) {
		var coverartUrl = channel.get("coverart").url();
		if(coverartUrl === ""){
			console.log("coverart url empty. can not generate a thumbnail.");
			return Parse.Promise.as();
		}
		console.log("generating thumbnail for " + channel.get("name") + ". Size: " + coverartAttribute);

		return Parse.Cloud.httpRequest({url: coverartUrl})
		.then(function(response) {
			var image = new Image();
			return image.setData(response.buffer);
		}).then(function(image) {
			return image.scale({ width: size, height: size });
		}).then(function(image) {
			return image.setFormat('JPEG');
		}).then(function(image) {
			return image.data();
		}).then(function(buffer) {
			console.log("Buffer returned, creating Parse File");
			var base64Buffer = buffer.toString("base64");
			var filename = channel.get("coverart").name() + "_thumbnail.jpg";
			var file = new Parse.File(filename, { base64: base64Buffer }, "image/jpeg");
			return file.save();
		}).then(function(file) {
			console.log("Thumbnail saved");
			channel.set(coverartAttribute, file);
		});
	}
	return Parse.Promise.as(); // this is already resolved promise
}
```
This worked fine as long as the images were stored in mongodb. Now I switched to s3 adapter and I see this error:

```
2017-05-20T13:14:01.562240+00:00 app[web.1]:   { Error: Command failed:
2017-05-20T13:14:01.562241+00:00 app[web.1]:       at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:289:17)
2017-05-20T13:14:01.562241+00:00 app[web.1]:       at emitTwo (events.js:106:13)
2017-05-20T13:14:01.562241+00:00 app[web.1]:       at ChildProcess.emit (events.js:194:7)
2017-05-20T13:14:01.562241+00:00 app[web.1]:       at maybeClose (internal/child_process.js:899:16)
2017-05-20T13:14:01.562242+00:00 app[web.1]:       at Socket.<anonymous> (internal/child_process.js:342:11)
2017-05-20T13:14:01.562242+00:00 app[web.1]:       at emitOne (events.js:96:13)
2017-05-20T13:14:01.562243+00:00 app[web.1]:       at Socket.emit (events.js:191:7)
2017-05-20T13:14:01.562243+00:00 app[web.1]:       at Pipe._handle.close [as _onclose] (net.js:511:12) code: 1, signal: null },
```

I confirmed that the `coverartUrl` is valid and does return a full size coverart image from amazon s3. I confirmed it is no issue with the upload to s3 because the full size coverart images are uploaded to s3 just fine.

It does not log "Buffer returned, creating Parse File".

**Comment by funkenstrahlen** [comment]
This was caused due to Parse.httpRequest not following redirects be default
