### ISSUE TITLE
Error: "Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found"

### ISSUE THREAD

**Issue by sraveh** [flovilmart/parse-image#4]
Hi @flovilmart ,

I'm getting the following error "Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found" when using parse-image locally.

I have both gm and ImageMagick installed:
convert --version
Version: ImageMagick 6.9.3-0 Q16 x86_64 2016-01-08 http://www.imagemagick.org
gm -version
GraphicsMagick 1.3.23 2015-11-07 Q8 http://www.GraphicsMagick.org/ 

When I try to run the test in the parse-image test folder, I get the following error:

```
/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse-image
==> mocha test

  Image
    #pad()
{ [Error: Command failed: gm identify: No decode delegate for this image format (/var/folders/sp/x6ptmcpd6x3djvgh5xyyj9jw0000gp/T/gmv9NvT7).
gm identify: Request did not return an image.
] code: 1, signal: null }
      1) should pad the image without error


  0 passing (35ms)
  1 failing

  1) Image #pad() should pad the image without error:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at test/test.js:35:4
      at Array.wrappedRejectedCallback (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:159:23)
      at ParsePromise.reject (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:89:35)
      at Array.wrappedRejectedCallback (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:175:19)
      at ParsePromise.reject (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:89:35)
      at Array.wrappedRejectedCallback (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:175:19)
      at ParsePromise.reject (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:89:35)
      at Array.wrappedRejectedCallback (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:175:19)
      at ParsePromise.reject (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:89:35)
      at Array.wrappedRejectedCallback (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:175:19)
      at ParsePromise.reject (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/parse/lib/browser/ParsePromise.js:89:35)
      at gm.<anonymous> (index.js:27:6)
      at gm.<anonymous> (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/gm/lib/getters.js:70:16)
      at cb (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/gm/lib/command.js:318:16)
      at ChildProcess.proc.on.onExit (/Users/simon.raveh/Development/Code/Projects/PettingClub/PettingClubParseBackend/node_modules/gm/lib/command.js:293:9)
      at maybeClose (internal/child_process.js:817:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at Pipe._onclose (net.js:469:12)

```

I know this more a gm/imagemagic issue but any help will be appreciated.

fyi: when I changed index.js from:

```
var gm = require('gm')
```

 to

```
var gm = require('gm').subClass({imageMagick: true})
```

The test passes. Since I'm new to nodejs, I'm not sure how to build a new version with this change included.

Thanks again for your help,
Simon

**Comment by flovilmart** [comment]
@sraveh check 0.1.1 on NPM, that should be fixed. I added a bunch of tests as well to make sure all is fine. Let me know

**Comment by sraveh** [comment]
Thanks @flovilmart everything works great now

**Comment by flovilmart** [comment]
np!

**Comment by ralphilius** [comment]
@flovilmart Not sure why this resurface on 0.2.0 now.. Can you please check or let me know any package/software I need to install manually?

**Comment by flovilmart** [comment]
I''m not sure either...

**Comment by AkankshaJadhav24** [comment]
@sraveh  : i still get same error

Error Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "./img.jpg" this most likely means the gm/convert binaries can't be found

Also, i used this line in my code : gm = require('gm').subClass({imageMagick: true});

Heres the piece of code : 

var fs = require('fs')
  , gm = require('gm').subClass({imageMagick: true});

gm('./img.jpg')
.size(function (err, size) {
	if (!err)
		console.log(size.width > size.height ? 'wider' : 'taller than you');
	else	
		console.log("Error "+  err);
});

**Comment by AkankshaJadhav24** [comment]
#sraveh  : i still get same error

Error Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "./img.jpg" this most likely means the gm/convert binaries can't be found

Also, i used this line in my code : gm = require('gm').subClass({imageMagick: true});

Heres the piece of code : 

var fs = require('fs')
  , gm = require('gm').subClass({imageMagick: true});

gm('./img.jpg')
.size(function (err, size) {
	if (!err)
		console.log(size.width > size.height ? 'wider' : 'taller than you');
	else	
		console.log("Error "+  err);
});

**Comment by newDeveloper27** [comment]
@sraveh  : i still get same error

Error Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "./img.jpg" this most likely means the gm/convert binaries can't be found

Also, i used this line in my code : gm = require('gm').subClass({imageMagick: true});

Heres the piece of code : 

var fs = require('fs')
  , gm = require('gm').subClass({imageMagick: true});

gm('./img.jpg')
.size(function (err, size) {
	if (!err)
		console.log(size.width > size.height ? 'wider' : 'taller than you');
	else	
		console.log("Error "+  err);
});

**Comment by yumo-mt** [comment]
@newDeveloper27  Is it settled now?
